version: "3.6"

services:
  sql:
    image: mysql:latest
    container_name: sql
    restart: always
    environment:
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=imse_sql_db
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    expose:
      - 8001
    ports:
      - 8001

  api:
    #this tells docker where to look for the Dockerfile to build the image
    build: ./Dataservice
    #name of your container and also the DNS name (nginx will proxy pass to this container from localhost:8000 when using a browser or Postman)
    container_name: rest-service
    restart: always
    #EXPOSE defines the ports reachable from INSIDE your docker network
    expose:
      - 8000
    ports:
      - 8000:3000
